/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'client-accounts': ClientAccountAuthOperations;
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    'contact-requests': ContactRequest;
    'crm-deals': CrmDeal;
    'crm-documents': CrmDocument;
    'crm-contacts': CrmContact;
    'crm-activities': CrmActivity;
    tickets: Ticket;
    'ticket-replies': TicketReply;
    'ticket-notes': TicketNote;
    'ticket-files': TicketFile;
    clients: Client;
    'client-accounts': ClientAccount;
    pages: Page;
    projects: Project;
    'case-studies': CaseStudy;
    media: Media;
    admins: Admin;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'contact-requests': ContactRequestsSelect<false> | ContactRequestsSelect<true>;
    'crm-deals': CrmDealsSelect<false> | CrmDealsSelect<true>;
    'crm-documents': CrmDocumentsSelect<false> | CrmDocumentsSelect<true>;
    'crm-contacts': CrmContactsSelect<false> | CrmContactsSelect<true>;
    'crm-activities': CrmActivitiesSelect<false> | CrmActivitiesSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    'ticket-replies': TicketRepliesSelect<false> | TicketRepliesSelect<true>;
    'ticket-notes': TicketNotesSelect<false> | TicketNotesSelect<true>;
    'ticket-files': TicketFilesSelect<false> | TicketFilesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'client-accounts': ClientAccountsSelect<false> | ClientAccountsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'social-links': SocialLink;
  };
  globalsSelect: {
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: ClientAccount | Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface ClientAccountAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Messages reçus par le formulaire Contact du site. Lecture seule : répondre par email ou téléphone.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-requests".
 */
export interface ContactRequest {
  id: number;
  name: string;
  company?: string | null;
  email: string;
  phone?: string | null;
  topic: string;
  service?: string | null;
  /**
   * Service consulté avant l’envoi du formulaire.
   */
  serviceLabel?: string | null;
  topicLabel?: string | null;
  message: string;
  notification?: ('not-configured' | 'pending' | 'sent' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Affaires en cours et conclues. Pipeline visuel : /crm/opportunites.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-deals".
 */
export interface CrmDeal {
  id: number;
  searchText?: string | null;
  title: string;
  client: number | Client;
  contact?: (number | null) | CrmContact;
  amount?: number | null;
  probability?: number | null;
  expectedClose?: string | null;
  stage: 'lead' | 'qualified' | 'proposal' | 'negotiation' | 'won' | 'lost';
  owner?: (number | null) | Admin;
  closedAt?: string | null;
  lostReason?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Entreprises clientes et prospects : utilisateurs, invitations et tickets sont gérés depuis la fiche ; le suivi commercial dans /crm.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  stage: 'prospect' | 'client' | 'inactive';
  /**
   * Suivi commercial : /crm/suivi.
   */
  pipeline?:
    ('to-contact' | 'contacted' | 'engaged' | 'need' | 'meeting' | 'quote' | 'on-hold' | 'won' | 'lost') | null;
  lostReason?: ('budget' | 'no-need' | 'competitor' | 'price' | 'no-answer' | 'timing' | 'other') | null;
  pipelineAt?: string | null;
  /**
   * Ce que l’entreprise demande. Repris dans les indicateurs commerciaux.
   */
  needs?: ('reseaux-cloud' | 'solutions-metier' | 'developpement-api' | 'maintenance-support' | 'autre')[] | null;
  /**
   * Contexte, périmètre, contraintes : ce qui ne tient pas dans les cases ci-dessus.
   */
  needsDetail?: string | null;
  owner?: (number | null) | Admin;
  source?: ('site-web' | 'recommandation' | 'prospection' | 'appel-offres' | 'partenaire' | 'salon' | 'autre') | null;
  sourceRequest?: (number | null) | ContactRequest;
  sector?: string | null;
  registration?: string | null;
  email?: string | null;
  phone?: string | null;
  website?: string | null;
  address?: string | null;
  city?: string | null;
  country?: string | null;
  notes?: string | null;
  searchText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name: string;
  /**
   * Complet : tout. CRM : /crm seulement (devis et factures en brouillon). Technicien : tickets Support seulement. Modifiable seulement par un gestionnaire des comptes, jamais sur son propre compte.
   */
  role: 'full' | 'crm' | 'technician';
  /**
   * Lecture, brouillons, envoi. Modifiable seulement par un gestionnaire des comptes, jamais sur son propre compte.
   */
  mailAccess: 'none' | 'read' | 'draft' | 'send';
  /**
   * Créer, modifier et supprimer les autres comptes et leurs droits. Indépendant du droit d’envoi.
   */
  manageAdmins?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * Interlocuteurs des entreprises. Interface complète : /crm/contacts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-contacts".
 */
export interface CrmContact {
  id: number;
  name: string;
  jobTitle?: string | null;
  client: number | Client;
  email?: string | null;
  phone?: string | null;
  primary?: boolean | null;
  notes?: string | null;
  searchText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Devis, factures (dont acomptes) et avoirs. Création, paiements, PDF et envoi : /crm/documents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-documents".
 */
export interface CrmDocument {
  id: number;
  kind: 'quote' | 'invoice' | 'credit';
  invoiceType?: ('standard' | 'deposit') | null;
  /**
   * Attribué à l’émission (envoi du devis, émission de la facture ou de l’avoir).
   */
  number?: string | null;
  status: 'draft' | 'sent' | 'accepted' | 'refused' | 'issued' | 'paid' | 'cancelled';
  title: string;
  client: number | Client;
  contact?: (number | null) | CrmContact;
  deal?: (number | null) | CrmDeal;
  sourceQuote?: (number | null) | CrmDocument;
  creditFor?: (number | null) | CrmDocument;
  issueDate?: string | null;
  validUntil?: string | null;
  dueDate?: string | null;
  lines?:
    | {
        description: string;
        quantity: number;
        unit?: string | null;
        unitPrice: number;
        vatRate?: number | null;
        id?: string | null;
      }[]
    | null;
  vatRate?: number | null;
  subtotal?: number | null;
  vat?: number | null;
  total?: number | null;
  payments?:
    | {
        date: string;
        amount: number;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  amountPaid?: number | null;
  balance?: number | null;
  conditions?: string | null;
  paidAt?: string | null;
  paymentNote?: string | null;
  notes?: string | null;
  searchText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Historique des échanges et tâches à faire. Suivi : /crm/taches.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-activities".
 */
export interface CrmActivity {
  id: number;
  searchText?: string | null;
  kind: 'call' | 'email' | 'whatsapp' | 'meeting' | 'note' | 'task';
  subject: string;
  details?: string | null;
  client: number | Client;
  deal?: (number | null) | CrmDeal;
  contact?: (number | null) | CrmContact;
  request?: (number | null) | ContactRequest;
  dueAt?: string | null;
  done?: boolean | null;
  /**
   * Envoyé à la personne assignée (sinon à l’auteur), si les rappels sont activés sur le serveur.
   */
  remind?: boolean | null;
  doneAt?: string | null;
  assignee?: (number | null) | Admin;
  author?: (number | null) | Admin;
  updatedAt: string;
  createdAt: string;
}
/**
 * Demandes ouvertes par les clients dans l’espace Support. Répondre au client ou ajouter une note interne en bas de chaque ticket.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  client: number | Client;
  author:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'client-accounts';
        value: number | ClientAccount;
      };
  subject: string;
  category: 'reseaux-cloud' | 'solutions-metier' | 'developpement-api' | 'maintenance-support' | 'autre';
  /**
   * Tri des tickets sur l’accueil du CRM.
   */
  priority: 'urgent' | 'high' | 'normal' | 'low';
  description: string;
  status: 'open' | 'in-progress' | 'waiting-client' | 'resolved' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * Personnes qui se connectent à l’espace Support. Pour inviter quelqu’un, ouvrir la fiche de son entreprise dans « Clients ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-accounts".
 */
export interface ClientAccount {
  id: number;
  name: string;
  client: number | Client;
  enabled?: boolean | null;
  invitedAt?: string | null;
  invitationHash?: string | null;
  invitationExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'client-accounts';
}
/**
 * Messages échangés avec le client, visibles par lui.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-replies".
 */
export interface TicketReply {
  id: number;
  client: number | Client;
  ticket: number | Ticket;
  author:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'client-accounts';
        value: number | ClientAccount;
      };
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Notes réservées à l’équipe, jamais montrées au client.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-notes".
 */
export interface TicketNote {
  id: number;
  ticket: number | Ticket;
  note: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pièces jointes des tickets (consultation et suppression seulement).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-files".
 */
export interface TicketFile {
  id: number;
  client: number | Client;
  ticket: number | Ticket;
  name: string;
  mime: string;
  bytes: number;
  storageKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Textes des pages du site. Chaque texte est repéré par sa clé ; modifier seulement la valeur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  slug: string;
  title: string;
  copy?:
    | {
        key: string;
        /**
         * Mission Afrique : laisser vide pour ne rien afficher. Les autres textes sont obligatoires.
         */
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cartes « Nos réalisations et projets » de l’accueil et de /realisations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  country: string;
  mission: string;
  status: 'completed' | 'contract' | 'ongoing' | 'upcoming';
  /**
   * Prioritaire sur le logo fourni avec le site.
   */
  logo?: (number | null) | Media;
  /**
   * Sans logo : le nom s’affiche en texte.
   */
  builtinLogo?: ('ina-guinee' | 'mairie-dakar' | 'rtg' | 'guce-anapi' | 'harmattan-erp' | 'cnts') | null;
  order?: number | null;
  published?: boolean | null;
  showOnHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Logos et visuels utilisés par les réalisations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Blocs détaillés avec visuel de la page /realisations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  client: string;
  category?: string | null;
  project: string;
  summary: string;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Prioritaire sur l’illustration fournie.
   */
  image?: (number | null) | Media;
  illustration?: ('infrastructure' | 'web') | null;
  anchor: string;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'contact-requests';
        value: number | ContactRequest;
      } | null)
    | ({
        relationTo: 'crm-deals';
        value: number | CrmDeal;
      } | null)
    | ({
        relationTo: 'crm-documents';
        value: number | CrmDocument;
      } | null)
    | ({
        relationTo: 'crm-contacts';
        value: number | CrmContact;
      } | null)
    | ({
        relationTo: 'crm-activities';
        value: number | CrmActivity;
      } | null)
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null)
    | ({
        relationTo: 'ticket-replies';
        value: number | TicketReply;
      } | null)
    | ({
        relationTo: 'ticket-notes';
        value: number | TicketNote;
      } | null)
    | ({
        relationTo: 'ticket-files';
        value: number | TicketFile;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'client-accounts';
        value: number | ClientAccount;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'client-accounts';
        value: number | ClientAccount;
      }
    | {
        relationTo: 'admins';
        value: number | Admin;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'client-accounts';
        value: number | ClientAccount;
      }
    | {
        relationTo: 'admins';
        value: number | Admin;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-requests_select".
 */
export interface ContactRequestsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  email?: T;
  phone?: T;
  topic?: T;
  service?: T;
  serviceLabel?: T;
  topicLabel?: T;
  message?: T;
  notification?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-deals_select".
 */
export interface CrmDealsSelect<T extends boolean = true> {
  searchText?: T;
  title?: T;
  client?: T;
  contact?: T;
  amount?: T;
  probability?: T;
  expectedClose?: T;
  stage?: T;
  owner?: T;
  closedAt?: T;
  lostReason?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-documents_select".
 */
export interface CrmDocumentsSelect<T extends boolean = true> {
  kind?: T;
  invoiceType?: T;
  number?: T;
  status?: T;
  title?: T;
  client?: T;
  contact?: T;
  deal?: T;
  sourceQuote?: T;
  creditFor?: T;
  issueDate?: T;
  validUntil?: T;
  dueDate?: T;
  lines?:
    | T
    | {
        description?: T;
        quantity?: T;
        unit?: T;
        unitPrice?: T;
        vatRate?: T;
        id?: T;
      };
  vatRate?: T;
  subtotal?: T;
  vat?: T;
  total?: T;
  payments?:
    | T
    | {
        date?: T;
        amount?: T;
        note?: T;
        id?: T;
      };
  amountPaid?: T;
  balance?: T;
  conditions?: T;
  paidAt?: T;
  paymentNote?: T;
  notes?: T;
  searchText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-contacts_select".
 */
export interface CrmContactsSelect<T extends boolean = true> {
  name?: T;
  jobTitle?: T;
  client?: T;
  email?: T;
  phone?: T;
  primary?: T;
  notes?: T;
  searchText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-activities_select".
 */
export interface CrmActivitiesSelect<T extends boolean = true> {
  searchText?: T;
  kind?: T;
  subject?: T;
  details?: T;
  client?: T;
  deal?: T;
  contact?: T;
  request?: T;
  dueAt?: T;
  done?: T;
  remind?: T;
  doneAt?: T;
  assignee?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  client?: T;
  author?: T;
  subject?: T;
  category?: T;
  priority?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-replies_select".
 */
export interface TicketRepliesSelect<T extends boolean = true> {
  client?: T;
  ticket?: T;
  author?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-notes_select".
 */
export interface TicketNotesSelect<T extends boolean = true> {
  ticket?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-files_select".
 */
export interface TicketFilesSelect<T extends boolean = true> {
  client?: T;
  ticket?: T;
  name?: T;
  mime?: T;
  bytes?: T;
  storageKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  stage?: T;
  pipeline?: T;
  lostReason?: T;
  pipelineAt?: T;
  needs?: T;
  needsDetail?: T;
  owner?: T;
  source?: T;
  sourceRequest?: T;
  sector?: T;
  registration?: T;
  email?: T;
  phone?: T;
  website?: T;
  address?: T;
  city?: T;
  country?: T;
  notes?: T;
  searchText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-accounts_select".
 */
export interface ClientAccountsSelect<T extends boolean = true> {
  name?: T;
  client?: T;
  enabled?: T;
  invitedAt?: T;
  invitationHash?: T;
  invitationExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  copy?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  mission?: T;
  status?: T;
  logo?: T;
  builtinLogo?: T;
  order?: T;
  published?: T;
  showOnHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  client?: T;
  category?: T;
  project?: T;
  summary?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  image?: T;
  illustration?: T;
  anchor?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  mailAccess?: T;
  manageAdmins?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  links?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'x' | 'youtube' | 'tiktok' | 'whatsapp';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  links?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}